# Generated by Django 3.1.7 on 2021-06-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_votemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='poll_voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
