# Generated by Django 3.1.7 on 2021-06-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_votemodel_poll_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votemodel',
            old_name='is_user_voted',
            new_name='which_user_voted',
        ),
    ]
