# Generated by Django 3.1.7 on 2021-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210622_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='first_option_count',
            new_name='first_option_count_middleagepeople',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='second_option_count',
            new_name='first_option_count_oldpeople',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='third_option_count',
            new_name='first_option_count_youngpeople',
        ),
        migrations.AddField(
            model_name='poll',
            name='first_option_count_youth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='second_option_count_middleagepeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='second_option_count_oldpeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='second_option_count_youngpeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='second_option_count_youth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='third_option_count_middleagepeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='third_option_count_oldpeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='third_option_count_youngpeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='third_option_count_youth',
            field=models.IntegerField(default=0),
        ),
    ]
