# Generated by Django 3.1.7 on 2021-06-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
