# Generated by Django 3.1.7 on 2021-06-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210621_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
